spring.application.name=compensation-api
spring.datasource.url= jdbc:postgresql://localhost:5432/compensation
spring.datasource.username= postgres
spring.datasource.password= root
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view= false
spring.flyway.enabled=true
management.endpoints.web.exposure.include=health